### ISSUE TITLE
Discord Server Invite

### ISSUE THREAD

**Issue by Posandu** [Lukas-Batema/Lukas-Batema#3]

**Comment by luni-moon** [comment]
> _No description provided._

Yeah, the discord server isn't ready yet, sadly. I am working on setting it up today though. Thanks for reminding me :)

**Comment by luni-moon** [comment]
Also, @Tronic247, if you want to, you can help me set up the discord server, when I get to it, since I didn't get to today. Just ping me in this comment section here!

**Comment by Posandu** [comment]
@Lukas-Batema send an email to [abwjxjlz0@relay.firefox.com](mailto:abwjxjlz0@relay.firefox.com) with an invite link to the server.

**Comment by luni-moon** [comment]
> @Lukas-Batema send an email to [abwjxjlz0@relay.firefox.com](mailto:abwjxjlz0@relay.firefox.com) with an invite link to the server.

Will do :)

**Comment by luni-moon** [comment]
I'm gonna keep this open for a reminder, until the discord server is completely set up...

**Comment by Posandu** [comment]
attention!

**Comment by luni-moon** [comment]
> attention!

Lol

**Comment by andrewstech** [comment]
![image](https://user-images.githubusercontent.com/45342431/148104103-70fb7d5c-36fa-4a93-b563-3eb46efbe257.png)

**Comment by luni-moon** [comment]
> ![image](https://user-images.githubusercontent.com/45342431/148104103-70fb7d5c-36fa-4a93-b563-3eb46efbe257.png)
> 
> 

Ok?

**Comment by luni-moon** [comment]
The server is now ready: [Invite](https://discord.gg/VdmjwwgBdW)
